### PR TITLE
update: Added Customer Metafields

### PR DESCRIPTION
**Pull request by berdjabrahamian**
Added Customer Metafields Implementation as its missing from the Metafields Actions

added:
- createCustomerMetafield
- getCustomerMetafieldsCount
- getCustomerMetafields

### CODE REVIEW

**Comment by berdjabrahamian** [comment]
@Razorsheep 
Is it possible to get this PR reviewed and discussed?
If any changes are required please let me know.

**Comment by berdjabrahamian** [comment]
@telkins 
@Razorsheep 
@twmbx 
@michaelvalentin 


Wanted to follow up on this PR and see if it can get reviewed and discussed.

Thanks

**Comment by telkins** [comment]
> @telkins @Razorsheep @twmbx @michaelvalentin
> 
> Wanted to follow up on this PR and see if it can get reviewed and discussed.
> 
> Thanks

Hi...sorry, but I don't work at signifly any longer.  There's not much I can do to help.  I'm not sure who's there any longer...other than @michaelvalentin .  I'm sure that when he sees these messages he'll figure something out.  🤓

**Comment by michaelvalentin** [comment]
Hi Travis and Berdj,

Let me reach out to the team and check about the status.

Best,

Michael
_

*Michael Valentin*
CEO & Partner

direct +45 2819 2966
office +45 6066 3110
email ***@***.***

Signifly <http://signifly.com/>⎪Vesterbrogade 44
***@***.***,12.5531097,17z/data=!3m1!4b1!4m5!3m4!1s0x46525321dd41a98f:0xc3a62be38c373c53!8m2!3d55.6727632!4d12.5552984>
⎪1620 København V
***@***.***,12.5531097,17z/data=!3m1!4b1!4m5!3m4!1s0x46525321dd41a98f:0xc3a62be38c373c53!8m2!3d55.6727632!4d12.5552984>

**Comment by agostinofiscale** [comment]
Dunno when this will be a thing in this repository, but I needed this. Thank you :)

**Comment by berdjabrahamian** [comment]
@Razorsheep 

Can we get an update on this PR please.

Thanks

**Pull request merged**
